/*
 * config_ignition.h
 *
 *  Created on: Jul 7, 2024
 *      Author: VHEMaster
 */

#ifndef CONFIG_INC_CONFIG_IGNITION_H_
#define CONFIG_INC_CONFIG_IGNITION_H_

#include "versioned_timings.h"

typedef enum {
  ECU_TIMING_IGNITION_READ_PARAM_GR1_START = 0,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_SATURATION_TIME = ECU_TIMING_IGNITION_READ_PARAM_GR1_START,


  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_START,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_SATURATION_TIME = ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_START,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_ADVANCE,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_END = ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_ADVANCE,

  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY_MAX_START,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY_MAX_END = ECU_TIMING_IGNITION_READ_PARAM_GR1_CY_MAX_START + ((ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_END - ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_START + 1) * (ECU_CYLINDER_MAX - 1)) - 1,

  ECU_TIMING_IGNITION_READ_PARAM_GR1_END = ECU_TIMING_IGNITION_READ_PARAM_GR1_CY_MAX_END,

  ECU_TIMING_IGNITION_READ_PARAM_GR_MAX_START,
  ECU_TIMING_IGNITION_READ_PARAM_GR_MAX_END = ECU_TIMING_IGNITION_READ_PARAM_GR_MAX_START + ((ECU_TIMING_IGNITION_READ_PARAM_GR1_END - ECU_TIMING_IGNITION_READ_PARAM_GR1_START + 1) * (IGNITION_CONFIG_GROUP_MAX - 1)) - 1,

  ECU_TIMING_IGNITION_READ_PARAM_MAX,
}ecu_timing_ignition_read_params_t;

typedef enum {
  ECU_TIMING_IGNITION_WRITE_PARAM_B1_START = 0,
  ECU_TIMING_IGNITION_WRITE_PARAM_B1_ALLOWED = ECU_TIMING_IGNITION_WRITE_PARAM_B1_START,
  ECU_TIMING_IGNITION_WRITE_PARAM_B1_ADVANCE,
  ECU_TIMING_IGNITION_WRITE_PARAM_B1_END = ECU_TIMING_IGNITION_WRITE_PARAM_B1_ADVANCE,

  ECU_TIMING_IGNITION_WRITE_PARAM_B_MAX_START,
  ECU_TIMING_IGNITION_WRITE_PARAM_B_MAX_END = ECU_TIMING_IGNITION_WRITE_PARAM_B_MAX_START + ((ECU_TIMING_IGNITION_WRITE_PARAM_B1_END - ECU_TIMING_IGNITION_WRITE_PARAM_B1_START + 1) * (ECU_BANK_MAX - 1)) - 1,
  ECU_TIMING_IGNITION_WRITE_PARAM_MAX,
}ecu_timing_ignition_write_params_t;

error_t ecu_timings_ignition_init(ecu_timing_ignition_t instance, ignition_ctx_t *ctx);
error_t ecu_timings_ignition_get_default_config(ecu_timing_ignition_t instance, ignition_config_t *config);
error_t ecu_timings_ignition_configure(ecu_timing_ignition_t instance, const ignition_config_t *config);
error_t ecu_timings_ignition_reset(ecu_timing_ignition_t instance);

error_t ecu_timings_ignition_get_runtime_data_ptr(ecu_timing_ignition_t instance, ignition_runtime_ctx_t **data);

#endif /* CONFIG_INC_CONFIG_IGNITION_H_ */
