/*
 * config_injection.h
 *
 *  Created on: Jul 7, 2024
 *      Author: VHEMaster
 */

#ifndef CONFIG_INC_CONFIG_INJECTION_H_
#define CONFIG_INC_CONFIG_INJECTION_H_

#include "versioned_timings.h"

typedef enum {
  ECU_TIMING_INJECTION_READ_PARAM_GR1_START = 0,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_PHASE_MEAN = ECU_TIMING_INJECTION_READ_PARAM_GR1_START,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_LAG_TIME,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_TIME_INJECT_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_DUTYCYCLE_MAX,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_DUTYCYCLE_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_ENRICHMENT_LATE_PHASE,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_INJECTOR_INPUT_PRESSURE_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_INJECTOR_OUTPUT_PRESSURE_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_INJECTOR_PRESSURE_DIFF_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_END = ECU_TIMING_INJECTION_READ_PARAM_GR1_INJECTOR_PRESSURE_DIFF_MEAN,

  ECU_TIMING_INJECTION_READ_PARAM_GR_MAX_START,
  ECU_TIMING_INJECTION_READ_PARAM_GR_MAX_END = ECU_TIMING_INJECTION_READ_PARAM_GR_MAX_START + ((ECU_TIMING_INJECTION_READ_PARAM_GR1_END - ECU_TIMING_INJECTION_READ_PARAM_GR1_START + 1) * (INJECTION_CONFIG_GROUP_MAX - 1)) - 1,

  ECU_TIMING_INJECTION_READ_PARAM_MAX,
}ecu_timing_injection_read_params_t;

typedef enum {
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_START = 0,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_ALLOWED = ECU_TIMING_INJECTION_WRITE_PARAM_B1_START,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_INJECTION_MASS,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_INJECTION_PHASE,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_END = ECU_TIMING_INJECTION_WRITE_PARAM_B1_INJECTION_PHASE,

  ECU_TIMING_INJECTION_WRITE_PARAM_B_MAX_START,
  ECU_TIMING_INJECTION_WRITE_PARAM_B_MAX_END = ECU_TIMING_INJECTION_WRITE_PARAM_B_MAX_START + ((ECU_TIMING_INJECTION_WRITE_PARAM_B1_END - ECU_TIMING_INJECTION_WRITE_PARAM_B1_START + 1) * (ECU_BANK_MAX - 1)) - 1,

  ECU_TIMING_INJECTION_WRITE_PARAM_MAX,
}ecu_timing_injection_write_params_t;

error_t ecu_timings_injection_init(ecu_timing_injection_t instance, injection_ctx_t *ctx);
error_t ecu_timings_injection_get_default_config(ecu_timing_injection_t instance, injection_config_t *config);
error_t ecu_timings_injection_configure(ecu_timing_injection_t instance, const injection_config_t *config);
error_t ecu_timings_injection_reset(ecu_timing_injection_t instance);

error_t ecu_timings_injection_get_runtime_data_ptr(ecu_timing_injection_t instance, injection_runtime_ctx_t **data);

#endif /* CONFIG_INC_CONFIG_INJECTION_H_ */
