/*
 * versioned_isotp.h
 *
 *  Created on: Oct 23, 2025
 *      Author: VHEMaster
 */

#ifndef CONFIG_VERSIONED_COMMUNICATION_INC_VERSIONED_ISOTP_H_
#define CONFIG_VERSIONED_COMMUNICATION_INC_VERSIONED_ISOTP_H_



#endif /* CONFIG_VERSIONED_COMMUNICATION_INC_VERSIONED_ISOTP_H_ */
