/*
 * config_timing.h
 *
 *  Created on: Jun 6, 2024
 *      Author: VHEMaster
 */

#ifndef CONFIG_INC_CONFIG_TIMING_H_
#define CONFIG_INC_CONFIG_TIMING_H_

#include "config_modules.h"
#include "timing.h"

#include "versioned_ignition.h"
#include "versioned_injection.h"

#define ECU_MODULES_TIMING_CALLBACKS_MAX   4

typedef enum {
  ECU_TIMING_TYPE_IGNITION,
  ECU_TIMING_TYPE_INJECTION,
  ECU_TIMING_TYPE_MAX
}ecu_timing_type_t;

typedef enum {
  ECU_MODULE_TIMING_READ_PARAM_MODE = 0,
  ECU_MODULE_TIMING_READ_PARAM_RPM,
  ECU_MODULE_TIMING_READ_PARAM_PERIOD,
  ECU_MODULE_TIMING_READ_PARAM_REVS_COUNT,
  ECU_MODULE_TIMING_READ_PARAM_MAX,
}ecu_module_timing_read_params_t;

typedef enum {
  ECU_TIMING_IGNITION_READ_PARAM_GR1_START = 0,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_SATURATION_TIME = ECU_TIMING_IGNITION_READ_PARAM_GR1_START,


  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_START,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_SATURATION_TIME = ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_START,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_ADVANCE,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_END = ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_ADVANCE,

  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY_MAX_START,
  ECU_TIMING_IGNITION_READ_PARAM_GR1_CY_MAX_END = ECU_TIMING_IGNITION_READ_PARAM_GR1_CY_MAX_START + ((ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_END - ECU_TIMING_IGNITION_READ_PARAM_GR1_CY1_START + 1) * (ECU_CYLINDER_MAX - 1)) - 1,

  ECU_TIMING_IGNITION_READ_PARAM_GR1_END = ECU_TIMING_IGNITION_READ_PARAM_GR1_CY_MAX_END,

  ECU_TIMING_IGNITION_READ_PARAM_GR_MAX_START,
  ECU_TIMING_IGNITION_READ_PARAM_GR_MAX_END = ECU_TIMING_IGNITION_READ_PARAM_GR_MAX_START + ((ECU_TIMING_IGNITION_READ_PARAM_GR1_END - ECU_TIMING_IGNITION_READ_PARAM_GR1_START + 1) * (ECU_CONFIG_IGNITION_GROUP_MAX - 1)) - 1,

  ECU_TIMING_IGNITION_READ_PARAM_MAX,
}ecu_timing_ignition_read_params_t;

typedef enum {
  ECU_TIMING_IGNITION_WRITE_PARAM_B1_START = 0,
  ECU_TIMING_IGNITION_WRITE_PARAM_B1_ALLOWED = ECU_TIMING_IGNITION_WRITE_PARAM_B1_START,
  ECU_TIMING_IGNITION_WRITE_PARAM_B1_ADVANCE,
  ECU_TIMING_IGNITION_WRITE_PARAM_B1_END = ECU_TIMING_IGNITION_WRITE_PARAM_B1_ADVANCE,

  ECU_TIMING_IGNITION_WRITE_PARAM_B_MAX_START,
  ECU_TIMING_IGNITION_WRITE_PARAM_B_MAX_END = ECU_TIMING_IGNITION_WRITE_PARAM_B_MAX_START + ((ECU_TIMING_IGNITION_WRITE_PARAM_B1_END - ECU_TIMING_IGNITION_WRITE_PARAM_B1_START + 1) * (ECU_BANK_MAX - 1)) - 1,
  ECU_TIMING_IGNITION_WRITE_PARAM_MAX,
}ecu_timing_ignition_write_params_t;

typedef enum {
  ECU_TIMING_INJECTION_READ_PARAM_GR1_START = 0,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_PHASE_MEAN = ECU_TIMING_INJECTION_READ_PARAM_GR1_START,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_LAG_TIME,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_TIME_INJECT_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_DUTYCYCLE_MAX,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_DUTYCYCLE_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_ENRICHMENT_LATE_PHASE,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_INJECTOR_INPUT_PRESSURE_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_INJECTOR_OUTPUT_PRESSURE_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_INJECTOR_PRESSURE_DIFF_MEAN,
  ECU_TIMING_INJECTION_READ_PARAM_GR1_END = ECU_TIMING_INJECTION_READ_PARAM_GR1_INJECTOR_PRESSURE_DIFF_MEAN,

  ECU_TIMING_INJECTION_READ_PARAM_GR_MAX_START,
  ECU_TIMING_INJECTION_READ_PARAM_GR_MAX_END = ECU_TIMING_INJECTION_READ_PARAM_GR_MAX_START + ((ECU_TIMING_INJECTION_READ_PARAM_GR1_END - ECU_TIMING_INJECTION_READ_PARAM_GR1_START + 1) * (ECU_CONFIG_INJECTION_GROUP_MAX - 1)) - 1,

  ECU_TIMING_INJECTION_READ_PARAM_MAX,
}ecu_timing_injection_read_params_t;

typedef enum {
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_START = 0,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_ALLOWED = ECU_TIMING_INJECTION_WRITE_PARAM_B1_START,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_ADVANCE,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_INJECTION_MASS,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_INJECTION_PHASE,
  ECU_TIMING_INJECTION_WRITE_PARAM_B1_END = ECU_TIMING_INJECTION_WRITE_PARAM_B1_INJECTION_PHASE,

  ECU_TIMING_INJECTION_WRITE_PARAM_B_MAX_START,
  ECU_TIMING_INJECTION_WRITE_PARAM_B_MAX_END = ECU_TIMING_INJECTION_WRITE_PARAM_B_MAX_START + ((ECU_TIMING_INJECTION_WRITE_PARAM_B1_END - ECU_TIMING_INJECTION_WRITE_PARAM_B1_START + 1) * (ECU_BANK_MAX - 1)) - 1,

  ECU_TIMING_INJECTION_WRITE_PARAM_MAX,
}ecu_timing_injection_write_params_t;

error_t ecu_modules_timing_init(ecu_module_timing_t instance, timing_ctx_t *ctx);
error_t ecu_modules_timing_get_default_config(ecu_module_timing_t instance, timing_config_t *config);
error_t ecu_modules_timing_configure(ecu_module_timing_t instance, const timing_config_t *config);
error_t ecu_modules_timing_reset(ecu_module_timing_t instance);

error_t ecu_modules_timing_register_cb(ecu_module_timing_t instance, timing_signal_update_cb_t callback, void *usrdata);

error_t ecu_modules_timing_get_data(ecu_module_timing_t instance, timing_data_t *data);
error_t ecu_modules_timing_get_diag(ecu_module_timing_t instance, timing_diag_t *diag);

#endif /* CONFIG_INC_CONFIG_TIMING_H_ */
